version: '3'

services:
  auth_server:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    image: auth_server
    container_name: auth_server_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    container_name: redis_container

  celery:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    container_name: celery_container
    command: celery -A rest_auth worker -l info
    depends_on:
      - auth_server
      - redis